Repository flooding-kr/flooding-frontend, pull requests merged in 2025-04, with the labels that each got.

#37 🔀시간표 get api 변경
  src/app/api/neis/schedule/[date]/route.ts
  src/entities/home/api/getSchedule.ts
  src/entities/home/api/index.ts
  src/entities/home/model/getDate.ts
  src/entities/home/model/useDateState.ts
  src/entities/home/model/useSchedule.ts
  src/entities/home/ui/MealBoard/index.tsx
  src/entities/home/ui/ScheduleBoard/index.tsx
  src/shared/types/schedule.ts
Labels: 📬 API, ✨ Feature

#38 🔀 홈베이스 신청 api 연결
  src/app/(pages)/homebase/page.tsx
  src/app/api/homebase/route.ts
  src/app/api/user/search/route.ts
  src/app/layout.tsx
  src/entities/homebase/api/getHomebasedata.ts
  src/entities/homebase/api/getUserSearch.ts
  src/entities/homebase/api/postHomebasedata.ts
  src/entities/homebase/store/useStore.tsx
  src/entities/homebase/ui/FilterSection/index.tsx
  src/entities/homebase/ui/SectionTitle/index.tsx
  src/entities/homebase/ui/StudentApplicationSection/index.tsx
  src/entities/homebase/ui/StudentSearchSection/index.tsx
  src/entities/homebase/ui/Table/index.tsx
  src/shared/assets/svg/Xbutton.tsx
  src/shared/assets/svg/index.ts
  src/shared/ui/Button/index.tsx
  src/shared/ui/Dropdown/index.tsx
  src/shared/ui/FilterContainer/index.tsx
  src/shared/ui/Header/index.tsx
  src/shared/ui/Tag/index.tsx
  src/shared/ui/modal/index.tsx
  src/widgets/homebase/ui/HomeBasePageWrapper/index.tsx
  src/widgets/homebase/ui/HomeBaseSection/index.tsx
Labels: 📬 API

#39 🔀 apply box progress bar의 z-index 수정 및 mobile footer z-index 추가
  src/entities/home/ui/ApplyBoard/index.tsx
  src/shared/ui/MobileFooter/index.tsx
Labels: 🐞 Bug, 🎨 Publishing

#40 🔀 동아리 페이지 퍼블리싱
  src/app/(pages)/club/page.tsx
  src/entities/club/ui/clubItem/index.tsx
  src/entities/club/ui/clubState/index.tsx
  src/entities/club/ui/createClubButton/index.tsx
  src/shared/assets/icons/Error.tsx
  src/shared/ui/FilterContainer/index.tsx
  src/views/club/index.ts
  src/views/club/ui/ClubPositioner/index.tsx
  src/views/club/ui/ClubWrapper/index.tsx
  src/views/club/ui/index.ts
  src/widgets/club/data/mockClub.ts
  src/widgets/club/index.ts
  src/widgets/club/types/clubListType.ts
  src/widgets/club/ui/allClubList/header/index.tsx
  src/widgets/club/ui/allClubList/index.tsx
  src/widgets/club/ui/clubList/index.tsx
  src/widgets/club/ui/index.ts
  src/widgets/club/ui/myClub/header/index.tsx
  src/widgets/club/ui/myClub/index.tsx
Labels: 🎨 Publishing

#43 🔀 pr 생성 시 디스코드 맨션 기능 추가
  .github/workflows/nodeJs-ci.yml
Labels: ⚡ Simple

#41 🔀 동아리 생성 폼 페이지 퍼블리싱
  src/app/(pages)/club/create/page.tsx
  src/entities/club/index.ts
  src/entities/club/model/index.ts
  src/entities/club/model/useShowImage.ts
  src/entities/club/store/index.ts
  src/entities/club/store/useImageStore.ts
  src/entities/club/ui/imageUploader/index.tsx
  src/entities/club/ui/index.ts
  src/shared/assets/icons/BigArrowLeft.tsx
  src/shared/assets/icons/ImageIcon.tsx
  src/shared/assets/icons/Trash.tsx
  src/shared/assets/icons/index.ts
  src/shared/ui/Dropdown/index.tsx
  src/shared/ui/Input/index.tsx
  src/shared/ui/TextArea/index.tsx
  src/shared/ui/index.ts
  src/views/createClub/index.ts
  src/views/createClub/ui/CreateClubPositioner/index.tsx
  src/views/createClub/ui/CreateClubWrapper/index.tsx
  src/views/createClub/ui/index.ts
  src/widgets/club/ui/createClub/form/imageList/index.tsx
  src/widgets/club/ui/createClub/form/index.tsx
  src/widgets/club/ui/createClub/header/index.tsx
  src/widgets/club/ui/createClub/index.ts
Labels: ✨ Feature, 🎨 Publishing

#46 🔀 image input 갯수 및 형식 제한
  src/entities/club/ui/imageUploader/index.tsx
Labels: 🐞 Bug

#48 🔀 급식판, 시간표 수정
  next.config.mjs
  src/app/api/neis/meal/route.ts
  src/app/api/neis/schedule/route.ts
  src/entities/home/api/getMeal.ts
  src/entities/home/api/getSchedule.ts
  src/entities/home/model/useMeal.ts
  src/entities/home/model/useSchedule.ts
  src/entities/home/ui/MealBoard/index.tsx
  src/entities/home/ui/ScheduleBoard/index.tsx
  src/shared/types/meal.ts
Labels: 📬 API, 🎨 Publishing

#49 🔀 동아리 상세 페이지 제작
  package-lock.json
  src/app/(pages)/club/[id]/page.tsx
  src/app/api/classroom/route.ts
  src/app/api/club/applicant/route.ts
  src/app/api/club/create-club/route.ts
  src/app/api/club/detail/route.ts
  src/app/api/image/route.ts
  src/entities/club/api/getClubList.ts
  src/entities/club/api/postImage.ts
  src/entities/club/model/handleMap.ts
  src/entities/club/model/index.ts
  src/entities/club/model/useClubList.ts
  src/entities/club/model/useMyClub.ts
  src/entities/club/model/useShowImage.ts
  src/entities/club/store/useClubTypeStore.ts
  src/entities/club/store/useImageStore.ts
  src/entities/club/ui/clubMember/index.tsx
  src/entities/club/ui/index.ts
  src/entities/club/ui/schoolMap/index.tsx
  src/shared/assets/icons/HeaderClub.tsx
  src/shared/assets/icons/KebabMenu.tsx
  src/shared/assets/icons/Map.tsx
  src/shared/assets/icons/index.ts
  src/shared/assets/png/auditoriumMap-1.png
  src/shared/assets/png/auditoriumMap-2.png
  src/shared/assets/png/auditoriumMap-3.png
  src/shared/assets/png/auditoriumMap-4.png
  src/shared/assets/png/dormitory-1.png
  src/shared/assets/png/dormitory-2.png
  src/shared/assets/png/index.ts
  src/shared/assets/png/mainMap-1.png
  src/shared/assets/png/mainMap-2.png
  src/shared/assets/png/mainMap-3.png
  src/shared/assets/png/mainMap-4.png
  src/shared/types/classroom.ts
  src/shared/types/club.ts
  src/shared/types/image.ts
  src/shared/types/types/clubListType.ts
  src/views/clubDetail/api/getClubDetail.ts
  src/views/clubDetail/model/useClubDetail.ts
  src/views/clubDetail/ui/Positioner/index.tsx
  src/views/clubDetail/ui/Wrapper/index.tsx
  src/widgets/club/api/getClassroom.ts
  src/widgets/club/api/postApplicant.ts
  src/widgets/club/api/postCreateClub.ts
  src/widgets/club/model/useClassroom.ts
  src/widgets/club/model/useClubForm.ts
  src/widgets/club/ui/clubDetail/content/index.tsx
  src/widgets/club/ui/clubDetail/header/detailModal/index.tsx
  src/widgets/club/ui/clubDetail/header/index.tsx
  src/widgets/club/ui/clubDetail/mapModal/index.tsx
  src/widgets/club/ui/clubDetail/recruitmentCard/index.tsx
  src/widgets/club/ui/clubList/index.tsx
  src/widgets/club/ui/createClub/form/index.tsx
  tailwind.config.ts
Labels: 📬 API, ✨ Feature, 🎨 Publishing
