Repository flooding-kr/flooding-frontend, pull requests merged in 2025-03, with the labels that each got.

#23 🔀 공지사항 페이지 제작
  src/app/notification/page.tsx
  src/app/page.tsx
  src/entities/notification/index.ts
  src/entities/notification/ui/NotificationItem/index.tsx
  src/entities/notification/ui/index.ts
  src/shared/assets/icons/ArrowUp.tsx
  src/shared/ui/FilterButton/index.tsx
  src/shared/ui/Header/index.tsx
  src/views/home/index.ts
  src/views/home/ui/home/index.tsx
  src/views/notification/index.ts
  src/views/notification/ui/notification/index.tsx
Labels: 🎨 Publishing

#26 🔀 회원가입 페이지 warning 해결
  src/shared/ui/Dropdown/index.tsx
  src/shared/ui/Input/index.tsx
Labels: 🐞 Bug

#27 🔀 useUser 훅 제작
  src/app/api/auth/sign-in/route.ts
  src/app/api/user/route.ts
  src/entities/home/ui/ProfileContainer/index.tsx
  src/shared/hooks/useUser.ts
  src/shared/stores/useUserStore.ts
  src/widgets/home/ui/OverviewPanel/index.tsx
  tsconfig.json
Labels: 📬 API

#28 🔀 급식판 수정
  next.config.mjs
  src/entities/home/api/getMeal.ts
  src/entities/home/ui/MealBoard/index.tsx
Labels: 📬 API, ✨ Feature

#29 🔀 토큰 저장 안됨 해결
  src/app/api/auth/sign-in/route.ts
Labels: 🐞 Bug

#30 🔀 header 수정
  src/shared/hooks/useUser.ts
  src/shared/ui/Header/index.tsx
Labels: ⚡ Simple

#32 🔀 프로필 이미지 모달 추가
  package-lock.json
  package.json
  src/entities/home/model/useProfileEdit.ts
  src/entities/home/ui/EditProfileModal/index.tsx
  src/entities/home/ui/ProfileContainer/index.tsx
  src/shared/assets/icons/AddButton.tsx
  src/shared/assets/icons/Trash.tsx
  src/shared/assets/icons/X.tsx
  src/shared/assets/icons/index.ts
  src/shared/ui/Portal/index.tsx
  tailwind.config.ts
Labels: 🎨 Publishing

#33 🔀 portal 추가
  src/app/(pages)/notification/page.tsx
  src/app/layout.tsx
Labels: 🐞 Bug

#34 🔀 메인페이지 스타일 정리
  src/entities/home/ui/ApplyBoard/index.tsx
  src/entities/home/ui/MealBoard/index.tsx
  src/entities/home/ui/ScheduleBoard/index.tsx
  src/entities/homebase/index.ts
  src/entities/verify/index.ts
  src/shared/assets/icons/HomebaseIcon.tsx
  src/views/home/ui/home/index.tsx
  src/views/signup/index.ts
  src/widgets/home/ui/DormitoryPanel/index.tsx
  src/widgets/signup/index.ts
Labels: ⚡ Simple

#35 🔀next 버전 업그레이드
  package-lock.json
  package.json
Labels: 0️⃣ Priority: Critical, ⚙ Setting

#36 🔀 수업 시간표 수업 탈출 오류 해결
  src/entities/home/ui/ScheduleBoard/index.tsx
Labels: ⚡ Simple
