Repository flooding-kr/flooding-frontend, pull requests merged in 2025-05, with the labels that each got.

#50 🔀 refresh token 재발급 오류 해결
  src/app/api/auth/re-issue/route.ts
  src/app/api/auth/sign-in/route.ts
  src/middleware.ts
  src/shared/libs/apiClient.ts
  src/shared/libs/getRefresh.ts
  src/shared/libs/is-vaild-token.ts
Labels: 📬 API, 🐞 Bug

#51 🔀 기숙사 페이지 퍼블리싱
  src/app/(pages)/dormitory/page.tsx
  src/app/globals.css
  src/entities/dormitory/index.ts
  src/entities/dormitory/ui/BorderDropdown/index.tsx
  src/entities/dormitory/ui/MusicItem/index.stories.tsx
  src/entities/dormitory/ui/MusicItem/index.tsx
  src/entities/dormitory/ui/StudentItem/index.stories.tsx
  src/entities/dormitory/ui/StudentItem/index.tsx
  src/entities/dormitory/ui/index.ts
  src/shared/assets/icons/ArrowDown.tsx
  src/shared/assets/icons/Book.tsx
  src/shared/assets/icons/Check.tsx
  src/shared/assets/icons/Hamburger.tsx
  src/shared/assets/icons/Massage.tsx
  src/shared/assets/icons/Music.tsx
  src/shared/assets/icons/index.ts
  src/views/dormitory/ui/Positioner/index.tsx
  src/views/dormitory/ui/Wrapper/index.tsx
  src/widgets/dormitory/ui/massage/footer/index.tsx
  src/widgets/dormitory/ui/massage/header/index.tsx
  src/widgets/dormitory/ui/massage/index.tsx
  src/widgets/dormitory/ui/music/footer/index.tsx
  src/widgets/dormitory/ui/music/header/index.tsx
  src/widgets/dormitory/ui/music/index.tsx
  src/widgets/dormitory/ui/music/list/index.tsx
  src/widgets/dormitory/ui/reservationList/index.tsx
  src/widgets/dormitory/ui/selfStudyBoard/footer/index.tsx
  src/widgets/dormitory/ui/selfStudyBoard/header/index.tsx
  src/widgets/dormitory/ui/selfStudyBoard/index.tsx
  tailwind.config.ts
Labels: 🎨 Publishing

#52 🔀 Side Bar 제작
  src/shared/assets/icons/Admin.tsx
  src/shared/assets/icons/HeaderNotification.tsx
  src/shared/assets/icons/index.ts
  src/shared/ui/Header/index.tsx
  src/shared/ui/Portal/index.tsx
  src/shared/ui/SideBar/index.tsx
Labels: 🎨 Publishing

#54 🔀 메인 페이지 반응형 및 api 연동
  src/app/(pages)/notifications/page.tsx
  src/entities/home/store/useNotifyStore.ts
  src/entities/home/ui/ApplyBoard/index.tsx
  src/entities/home/ui/MealBoard/index.tsx
  src/entities/home/ui/ScheduleBoard/index.tsx
  src/shared/assets/icons/Book.tsx
  src/shared/assets/icons/Error.tsx
  src/shared/assets/icons/Massage.tsx
  src/shared/assets/icons/Music.tsx
  src/shared/types/home.ts
  src/shared/ui/Portal/index.tsx
  src/widgets/club/ui/allClubList/index.tsx
  src/widgets/club/ui/clubDetail/mapModal/index.tsx
  src/widgets/club/ui/myClub/index.tsx
  src/widgets/dormitory/ui/massage/footer/index.tsx
  src/widgets/dormitory/ui/massage/header/index.tsx
  src/widgets/dormitory/ui/music/header/index.tsx
  src/widgets/dormitory/ui/selfStudyBoard/footer/index.tsx
  src/widgets/dormitory/ui/selfStudyBoard/header/index.tsx
  src/widgets/home/api/getMassage.ts
  src/widgets/home/api/getSelfStudy.ts
  src/widgets/home/api/postMassage.ts
  src/widgets/home/api/postSelfStudy.ts
  src/widgets/home/model/useDispatchMassage.ts
  src/widgets/home/model/useDispatchSelfStudy.ts
  src/widgets/home/model/useFetchMassage.ts
  src/widgets/home/model/useFetchSelfStudy.ts
  src/widgets/home/ui/DormitoryPanel/index.tsx
  src/widgets/home/ui/massageNotifyModal/index.tsx
  src/widgets/home/ui/selfStudyNotifyModal/index.tsx
Labels: 📬 API, ✨ Feature, 🎨 Publishing

#56 🔀 회원가입 학생/선생님 구분
  src/app/api/auth/student/sign-up/route.ts
  src/app/api/auth/teacher/sign-up/route.ts
  src/entities/signup/api/postSignup.ts
  src/entities/signup/model/formType.ts
  src/entities/signup/model/useSignup.ts
  src/entities/signup/ui/SignupForm/index.tsx
  src/shared/hooks/useUser.ts
Labels: 📬 API

#57 🔀 기숙사 신청 취소 기능 생성
  public/favicon.ico
  src/app/_component/LayoutWrapper.tsx
  src/app/layout.tsx
  src/entities/home/model/checkApply.ts
  src/entities/home/ui/ApplyBoard/index.tsx
  src/entities/home/ui/ProfileContainer/index.tsx
  src/shared/types/home.ts
  src/shared/ui/Dropdown/index.tsx
  src/widgets/dormitory/api/deleteMassage.ts
  src/widgets/dormitory/api/deleteSelfStudy.ts
  src/widgets/dormitory/ui/massage/footer/index.tsx
  src/widgets/dormitory/ui/massage/index.tsx
  src/widgets/dormitory/ui/selfStudyBoard/footer/index.tsx
  src/widgets/dormitory/ui/selfStudyBoard/index.tsx
  src/widgets/home/ui/DormitoryPanel/index.tsx
  tailwind.config.ts
  tsconfig.json
Labels: 📬 API

#59 🔀 헤더 관리자 확인 기능 추가
  src/shared/ui/FilterContainer/index.tsx
  src/shared/ui/Header/index.tsx
Labels: 🐞 Bug

#61 🔀 예약된 table 마감 수정
  src/entities/homebase/ui/Table/index.tsx
Labels: 🐞 Bug

#63 🔀 메인 페이지 반응형 수정
  src/entities/home/model/useMeal.ts
  src/entities/home/ui/MealBoard/index.tsx
  src/entities/home/ui/ProfileContainer/index.tsx
  src/entities/home/ui/ScheduleBoard/index.tsx
  src/views/home/ui/home/index.tsx
  src/widgets/home/ui/DormitoryPanel/index.tsx
  src/widgets/home/ui/OverviewPanel/index.tsx
Labels: ✨ Feature

#68 🔀 급식판 표시 에러
  src/entities/home/ui/MealBoard/index.tsx
Labels: 🐞 Bug

#69 🔀Deploy
  src/entities/home/ui/MealBoard/index.tsx
Labels: 🌏 Deploy

#70 🔀 급식표 초기값 변경
  src/entities/home/ui/MealBoard/index.tsx
Labels: 🐞 Bug

#72 🔀 dailyMeal use State 초기값 설정
  src/entities/home/ui/MealBoard/index.tsx
  src/shared/assets/icons/DormitoryIcon.tsx
  src/shared/ui/Button/index.tsx
Labels: 🐞 Bug

#86 🔀 마이페이지 width 수정
  src/entities/home/ui/ProfileContainer/index.tsx
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#91 🔀 좋아요 클릭 시 움직이는 아이콘 변경
  src/entities/dormitory/ui/MusicItem/index.tsx
Labels: 🐞 Bug, 🎨 Publishing

#89 🔀 기상 음악 신청 로딩 추가
  src/widgets/dormitory/model/useDispatchMusic.ts
  src/widgets/dormitory/ui/music/footer/index.tsx
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#83 🔀 개인정보처리방침 아이콘 가시화
  src/shared/ui/Checkbox/index.tsx
Labels: 🐞 Bug

#93 🔀 사유 글씨 제한 텍스트와 총 인원 텍스트가 겹치는 이슈 해결
  src/entities/homebase/ui/StudentApplicationSection/index.tsx
Labels: 0️⃣ Priority: Critical

#94 🔀 Deploy
  src/entities/dormitory/ui/MusicItem/index.tsx
  src/entities/home/ui/ProfileContainer/index.tsx
  src/entities/homebase/ui/StudentApplicationSection/index.tsx
  src/shared/ui/Checkbox/index.tsx
  src/widgets/dormitory/model/useDispatchMusic.ts
  src/widgets/dormitory/ui/music/footer/index.tsx
Labels: 0️⃣ Priority: Critical, 🐞 Bug, 🌏 Deploy

#108 🔀 좋아요 아이콘 크기 조정
  src/entities/dormitory/ui/MusicItem/index.tsx
Labels: 🐞 Bug, 🎨 Publishing

#106 🔀 급식 대쉬보드 이슈 수정
  package-lock.json
  package.json
  src/app/_provider/TanstackProvider.tsx
  src/entities/home/model/useMeal.ts
  src/entities/home/ui/MealBoard/index.tsx
  src/entities/home/ui/ScheduleBoard/index.tsx
  tsconfig.json
Labels: 🐞 Bug, ✨ Feature

#121 🔀 개인정보 처리방침 모달 추가
  src/entities/signup/ui/PrivacyPolicyModal/index.tsx
  src/entities/signup/ui/SignupCheckbox/index.tsx
  src/entities/signup/ui/SignupForm/index.tsx
  src/shared/assets/icons/CheckBoxTrue.tsx
Labels: 🐞 Bug, 🎨 Publishing

#125 🔀 Deploy
  src/entities/dormitory/model/useAdminDeleteMusic.ts
  src/entities/dormitory/model/useDeleteMusic.ts
  src/entities/dormitory/ui/MusicItem/index.tsx
  src/entities/signup/ui/PrivacyPolicyModal/index.tsx
  src/entities/signup/ui/SignupCheckbox/index.tsx
  src/entities/signup/ui/SignupForm/index.tsx
  src/shared/assets/icons/BigArrowRight.tsx
  src/shared/assets/icons/CheckBoxTrue.tsx
  src/widgets/dormitory/model/useDispatchMusic.ts
  src/widgets/dormitory/store/useMusicTypeStore.ts
  src/widgets/dormitory/ui/music/header/index.tsx
  src/widgets/dormitory/ui/music/index.tsx
  src/widgets/dormitory/ui/music/list/index.tsx
Labels: 🌏 Deploy

#129 🔀 기상음악 기본 정렬 수정
  src/widgets/dormitory/ui/music/header/index.tsx
Labels: ⚡ Simple

#128 🔀 기상음악 공지사항 수정
  src/widgets/dormitory/ui/music/notify/index.tsx
Labels: ⚡ Simple

#132 🔀 Deploy
  package-lock.json
  src/app/(pages)/dormitory/music/page.tsx
  src/shared/assets/svg/HeaderLogo.tsx
  src/shared/ui/Header/index.tsx
  src/views/music/ui/index.tsx
  src/widgets/dormitory/model/useFetchMusic.ts
  src/widgets/dormitory/ui/music/header/index.tsx
  src/widgets/dormitory/ui/music/notify/index.tsx
Labels: 🌏 Deploy

#134 🔀 workflow 수정
  .github/CODEOWNERS
  .github/workflows/nodeJs-ci.yml
Labels: ⚙ Setting
