Repository flooding-kr/flooding-frontend, pull requests merged in 2025-02, with the labels that each got.

#3 🔀 provider에 use client 추가
  src/app/_provider/TanstackProvider.tsx
Labels: 🐞 Bug

#5 🔀 fontSize title 변경
  tailwind.config.ts
Labels: ⚙ Setting, ⚡ Simple

#7 🔀 로그인 페이지 퍼블리싱
  src/app/(pages)/signin/page.tsx
  src/app/globals.css
  src/entities/signIn/index.tsx
  src/entities/signIn/ui/SigninForm/index.tsx
  src/entities/signIn/ui/SigninPrompt/index.tsx
  src/shared/assets/icons/Eye.tsx
  src/shared/assets/icons/EyeClose.tsx
  src/shared/assets/svg/SignInLogo.tsx
  src/shared/assets/svg/VerticalLine.tsx
  src/shared/assets/svg/index.ts
  src/views/signIn/index.tsx
  src/views/signIn/ui/signIn/index.tsx
  src/widgets/signIn/index.tsx
  src/widgets/signIn/ui/signIn/index.tsx
  tailwind.config.ts
Labels: 🎨 Publishing, ⚡ Simple

#8 🔀 체크박스 컴포넌트 제작
  src/entities/signIn/ui/SigninForm/index.tsx
  src/shared/assets/icons/CheckBoxFalse.tsx
  src/shared/assets/icons/CheckBoxTrue.tsx
  src/shared/assets/icons/index.ts
  src/shared/ui/Button/index.tsx
  src/shared/ui/Checkbox/index.tsx
  src/shared/ui/index.ts
Labels: 🎨 Publishing

#9 🔀 dropdown 컴포넌트 퍼블리싱
  src/entities/signIn/ui/SigninForm/index.tsx
  src/shared/assets/icons/ArrowDown.tsx
  src/shared/assets/icons/ArrowLeft.tsx
  src/shared/assets/icons/ArrowRight.tsx
  src/shared/assets/icons/ArrowUp.tsx
  src/shared/assets/icons/index.ts
  src/shared/ui/Dropdown/index.tsx
  src/shared/ui/index.ts
Labels: 🎨 Publishing

#10 🔀 학생 검색 input 퍼블리싱
  .eslintrc.json
  .github/workflows/nodeJs-ci.yml
  .storybook/preview.ts
  src/app/(pages)/homebase/page.tsx
  src/shared/assets/icons/Search.tsx
  src/shared/assets/icons/index.ts
  src/shared/hooks/useDebounce.ts
  src/shared/ui/FilterButton/index.tsx
  src/shared/ui/SearchInput/index.stories.tsx
  src/shared/ui/SearchInput/index.tsx
  src/shared/ui/index.ts
Labels: ✨ Feature, 🎨 Publishing

#11 🔀 Tag 컴포넌트 제작
  src/app/(pages)/homebase/page.tsx
  src/shared/ui/Tag/index.tsx
  src/shared/ui/index.ts
Labels: 🎨 Publishing

#12 🔀 필터 버튼 추가
  src/shared/assets/icons/Filter.tsx
  src/shared/assets/icons/index.ts
  src/shared/ui/FilterButton/index.stories.tsx
  src/shared/ui/FilterButton/index.tsx
Labels: 🎨 Publishing

#14 🔀 홈베이스 퍼블리싱
  src/app/(pages)/homebase/page.tsx
  src/entities/homebase/data/table.tsx
  src/entities/homebase/index.tsx
  src/entities/homebase/store/useStore.tsx
  src/entities/homebase/ui/FilterSection/index.tsx
  src/entities/homebase/ui/SectionTitle/index.tsx
  src/entities/homebase/ui/StudentApplicationSection/index.tsx
  src/entities/homebase/ui/StudentSearchSection/index.tsx
  src/entities/homebase/ui/Table/index.tsx
  src/shared/assets/icons/AddButton.tsx
  src/shared/assets/icons/CloseButton.tsx
  src/shared/assets/icons/HomebaseIcon.tsx
  src/shared/assets/icons/InfoCircle.tsx
  src/shared/assets/icons/InfoCircleBig.tsx
  src/shared/assets/icons/index.ts
  src/shared/assets/svg/VerticalLineBig.tsx
  src/shared/assets/svg/index.ts
  src/shared/ui/FilterContainer/index.tsx
  src/shared/ui/Tag/index.tsx
  src/shared/ui/index.ts
  src/widgets/homebase/index.tsx
  src/widgets/homebase/ui/HomeBasePageWrapper/index.tsx
  src/widgets/homebase/ui/HomeBaseSection/index.tsx
Labels: ✨ Feature, 🎨 Publishing

#15 🔀 자습 신청, 안마의자 신청 보드 퍼블리싱
  src/app/layout.tsx
  src/app/page.tsx
  src/entities/home/ui/ApplyBoard/index.tsx
  src/shared/assets/icons/Error.tsx
  src/shared/assets/icons/index.ts
  src/shared/ui/Button/index.tsx
Labels: 🎨 Publishing

#16 🔀 헤더 제작
  src/app/layout.tsx
  src/shared/assets/icons/HeaderAttendance.tsx
  src/shared/assets/icons/HeaderClub.tsx
  src/shared/assets/icons/HeaderDormitory.tsx
  src/shared/assets/icons/HeaderHomebase.tsx
  src/shared/assets/icons/HeaderManager.tsx
  src/shared/assets/icons/HeaderNotification.tsx
  src/shared/assets/icons/HeaderTotal.tsx
  src/shared/assets/icons/index.ts
  src/shared/assets/svg/HeaderLogo.tsx
  src/shared/assets/svg/index.ts
  src/shared/ui/FilterContainer/index.tsx
  src/shared/ui/Header/index.tsx
  src/shared/ui/index.ts
Labels: ✨ Feature, 🎨 Publishing

#17 🔀 기상 음악 아이템 컴포넌트 제작
  src/app/layout.tsx
  src/entities/dormitory/ui/SongItem/index.stories.tsx
  src/entities/dormitory/ui/SongItem/index.tsx
  src/entities/home/ui/ApplyBoard/index.tsx
  src/shared/assets/icons/Like.tsx
  src/shared/assets/icons/index.ts
Labels: 🎨 Publishing

#18 🔀모바일 footer 제작
  src/app/layout.tsx
  src/shared/assets/icons/FooterHome.tsx
  src/shared/assets/icons/HeaderAttendance.tsx
  src/shared/assets/icons/HeaderClub.tsx
  src/shared/assets/icons/HeaderDormitory.tsx
  src/shared/assets/icons/HeaderHomebase.tsx
  src/shared/assets/icons/index.ts
  src/shared/ui/Header/index.tsx
  src/shared/ui/MoblieFooter/index.tsx
  src/shared/ui/index.ts
Labels: 🎨 Publishing

#21 🔀 홈페이지 퍼블리싱
  src/app/page.tsx
  src/entities/home/api/getDate.ts
  src/entities/home/api/getMeal.ts
  src/entities/home/api/getSchedule.ts
  src/entities/home/api/index.ts
  src/entities/home/index.ts
  src/entities/home/ui/ApplyBoard/index.tsx
  src/entities/home/ui/MealBoard/index.tsx
  src/entities/home/ui/ProfileContainer/index.tsx
  src/entities/home/ui/ScheduleBoard/index.tsx
  src/entities/home/ui/index.ts
  src/shared/assets/icons/BigArrowRight.tsx
  src/shared/assets/icons/DormitoryIcon.tsx
  src/shared/assets/icons/index.ts
  src/shared/assets/svg/VerticalLineBig.tsx
  src/views/home/ui/index.tsx
  src/widgets/home/index.ts
  src/widgets/home/ui/DormitoryPanel/index.tsx
  src/widgets/home/ui/OverviewPanel/index.tsx
Labels: 🎨 Publishing

#22 🔀 로그인, 로그아웃 api 연결
  package-lock.json
  package.json
  src/app/(pages)/signup/auth/verify/page.tsx
  src/app/(pages)/signup/page.tsx
  src/app/api/auth/re-issue/route.ts
  src/app/api/auth/re-verify/route.ts
  src/app/api/auth/sign-in/route.ts
  src/app/api/auth/sign-up/route.ts
  src/app/api/auth/verify/route.ts
  src/app/layout.tsx
  src/entities/signIn/api/postSignin.ts
  src/entities/signIn/api/signin.ts
  src/entities/signIn/model/showError.ts
  src/entities/signIn/model/useSignin.ts
  src/entities/signIn/ui/SigninForm/index.tsx
  src/entities/signIn/ui/SigninPrompt/index.tsx
  src/entities/signup/api/postSignup.ts
  src/entities/signup/model/formType.ts
  src/entities/signup/model/showError.ts
  src/entities/signup/model/useSignup.ts
  src/entities/signup/store/useStore.tsx
  src/entities/signup/ui/CertificationSection/index.tsx
  src/entities/signup/ui/DropdownField/index.tsx
  src/entities/signup/ui/SignupCheckbox/index.tsx
  src/entities/signup/ui/SignupForm/index.tsx
  src/entities/signup/ui/SignupFormElements/index.tsx
  src/entities/signup/ui/SignupGenderToggle/index.tsx
  src/entities/signup/ui/SignupRoleToggle/index.tsx
  src/entities/signup/ui/SignupSection/index.tsx
  src/entities/signup/ui/SignupStudentFields/index.tsx
  src/entities/signup/ui/index.tsx
  src/entities/verify/api/getReVerify.ts
  src/entities/verify/api/getVerify.ts
  src/entities/verify/index.tsx
  src/entities/verify/model/showError.ts
  src/entities/verify/model/useReVerify.ts
  src/entities/verify/model/useVerify.ts
  src/entities/verify/ui/Verify/index.tsx
  src/shared/assets/icons/CheckBoxFalse.tsx
  src/shared/assets/svg/CertificationLogo.tsx
  src/shared/assets/svg/SignupLogo.tsx
  src/shared/assets/svg/index.ts
  src/shared/libs/apiClient.ts
  src/shared/libs/getRefresh.ts
  src/shared/ui/Button/index.tsx
  src/shared/ui/Checkbox/index.tsx
  src/shared/ui/Dropdown/index.tsx
  src/shared/ui/Input/index.tsx
  src/shared/ui/MobileFooter/index.tsx
  src/shared/ui/ToggleButton/index.tsx
  src/shared/ui/index.ts
  src/views/signup/index.tsx
  src/views/signup/ui/signup/index.tsx
  src/views/verify/index.tsx
  src/views/verify/ui/verify/index.tsx
  src/widgets/signup/index.tsx
  src/widgets/signup/ui/signup/index.tsx
  src/widgets/verify/index.tsx
  src/widgets/verify/ui/verify/index.tsx
Labels: 📬 API
